name: PDF Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: forkbabu/AutoEdit@master
        with:
          path: "tests/main.tex"
      - uses: actions/upload-artifact@v1
        with: 
          name: rendered_file
          path: rendered_output
